/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.repository.domain.tables.records;


import com.ep.domain.repository.domain.enums.EpSystemDictStatus;
import com.ep.domain.repository.domain.tables.EpSystemDict;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EpSystemDictRecord extends UpdatableRecordImpl<EpSystemDictRecord> implements Record13<Long, String, String, String, String, String, Integer, EpSystemDictStatus, Timestamp, Timestamp, String, Boolean, Long> {

    private static final long serialVersionUID = 367912715;

    /**
     * Create a detached EpSystemDictRecord
     */
    public EpSystemDictRecord() {
        super(EpSystemDict.EP_SYSTEM_DICT);
    }

    /**
     * Create a detached, initialised EpSystemDictRecord
     */
    public EpSystemDictRecord(Long id, String label, String groupName, String key, String value, String description, Integer sort, EpSystemDictStatus status, Timestamp createAt, Timestamp updateAt, String remark, Boolean delFlag, Long version) {
        super(EpSystemDict.EP_SYSTEM_DICT);

        set(0, id);
        set(1, label);
        set(2, groupName);
        set(3, key);
        set(4, value);
        set(5, description);
        set(6, sort);
        set(7, status);
        set(8, createAt);
        set(9, updateAt);
        set(10, remark);
        set(11, delFlag);
        set(12, version);
    }

    /**
     * Getter for <code>ep.ep_system_dict.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ep.ep_system_dict.id</code>.
     */
    public EpSystemDictRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_system_dict.label</code>. 标签名
     */
    public String getLabel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ep.ep_system_dict.label</code>. 标签名
     */
    public EpSystemDictRecord setLabel(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_system_dict.group_name</code>. 组名
     */
    public String getGroupName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ep.ep_system_dict.group_name</code>. 组名
     */
    public EpSystemDictRecord setGroupName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_system_dict.key</code>. key
     */
    public String getKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ep.ep_system_dict.key</code>. key
     */
    public EpSystemDictRecord setKey(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_system_dict.value</code>. 数据值
     */
    public String getValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ep.ep_system_dict.value</code>. 数据值
     */
    public EpSystemDictRecord setValue(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_system_dict.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ep.ep_system_dict.description</code>. 描述
     */
    public EpSystemDictRecord setDescription(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_system_dict.sort</code>. 排序
     */
    public Integer getSort() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ep.ep_system_dict.sort</code>. 排序
     */
    public EpSystemDictRecord setSort(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_system_dict.status</code>.
     */
    public EpSystemDictStatus getStatus() {
        return (EpSystemDictStatus) get(7);
    }

    /**
     * Setter for <code>ep.ep_system_dict.status</code>.
     */
    public EpSystemDictRecord setStatus(EpSystemDictStatus value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_system_dict.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>ep.ep_system_dict.create_at</code>. 创建时间
     */
    public EpSystemDictRecord setCreateAt(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_system_dict.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>ep.ep_system_dict.update_at</code>. 更新时间
     */
    public EpSystemDictRecord setUpdateAt(Timestamp value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_system_dict.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ep.ep_system_dict.remark</code>. 备注
     */
    public EpSystemDictRecord setRemark(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_system_dict.del_flag</code>. 删除标记
     */
    public Boolean getDelFlag() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>ep.ep_system_dict.del_flag</code>. 删除标记
     */
    public EpSystemDictRecord setDelFlag(Boolean value) {
        set(11, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>ep.ep_system_dict.version</code>.
     */
    public Long getVersion() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>ep.ep_system_dict.version</code>.
     */
    public EpSystemDictRecord setVersion(Long value) {
        set(12, value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, String, String, Integer, EpSystemDictStatus, Timestamp, Timestamp, String, Boolean, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, String, String, Integer, EpSystemDictStatus, Timestamp, Timestamp, String, Boolean, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EpSystemDict.EP_SYSTEM_DICT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EpSystemDict.EP_SYSTEM_DICT.LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EpSystemDict.EP_SYSTEM_DICT.GROUP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return EpSystemDict.EP_SYSTEM_DICT.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return EpSystemDict.EP_SYSTEM_DICT.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return EpSystemDict.EP_SYSTEM_DICT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return EpSystemDict.EP_SYSTEM_DICT.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EpSystemDictStatus> field8() {
        return EpSystemDict.EP_SYSTEM_DICT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return EpSystemDict.EP_SYSTEM_DICT.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return EpSystemDict.EP_SYSTEM_DICT.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return EpSystemDict.EP_SYSTEM_DICT.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return EpSystemDict.EP_SYSTEM_DICT.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return EpSystemDict.EP_SYSTEM_DICT.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGroupName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictStatus value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value2(String value) {
        setLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value3(String value) {
        setGroupName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value4(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value5(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value6(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value7(Integer value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value8(EpSystemDictStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value9(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value10(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value11(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value12(Boolean value) {
        setDelFlag(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord value13(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpSystemDictRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Integer value7, EpSystemDictStatus value8, Timestamp value9, Timestamp value10, String value11, Boolean value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }
}
