/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.repository.domain.tables.records;


import com.ep.domain.repository.domain.tables.EpWechatPayRefund;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 微信支付退单表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EpWechatPayRefundRecord extends UpdatableRecordImpl<EpWechatPayRefundRecord> {

    private static final long serialVersionUID = 1761038812;

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.id</code>. 主键
     */
    public EpWechatPayRefundRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.appid</code>. appid
     */
    public EpWechatPayRefundRecord setAppid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.appid</code>. appid
     */
    public String getAppid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.mch_id</code>. 商户号
     */
    public EpWechatPayRefundRecord setMchId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.mch_id</code>. 商户号
     */
    public String getMchId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.out_trade_no</code>. 商户订单号
     */
    public EpWechatPayRefundRecord setOutTradeNo(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.out_trade_no</code>. 商户订单号
     */
    public String getOutTradeNo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.transaction_id</code>. 微信订单号
     */
    public EpWechatPayRefundRecord setTransactionId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.transaction_id</code>. 微信订单号
     */
    public String getTransactionId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.out_refund_no</code>. 商户退款单号
     */
    public EpWechatPayRefundRecord setOutRefundNo(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.out_refund_no</code>. 商户退款单号
     */
    public String getOutRefundNo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.total_fee</code>. 订单金额
     */
    public EpWechatPayRefundRecord setTotalFee(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.total_fee</code>. 订单金额
     */
    public Integer getTotalFee() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.refund_fee</code>. 退款金额
     */
    public EpWechatPayRefundRecord setRefundFee(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.refund_fee</code>. 退款金额
     */
    public Integer getRefundFee() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.refund_desc</code>. 退款原因
     */
    public EpWechatPayRefundRecord setRefundDesc(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.refund_desc</code>. 退款原因
     */
    public String getRefundDesc() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.return_code</code>. 返回状态码
     */
    public EpWechatPayRefundRecord setReturnCode(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.return_code</code>. 返回状态码
     */
    public String getReturnCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.return_msg</code>. 返回信息
     */
    public EpWechatPayRefundRecord setReturnMsg(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.return_msg</code>. 返回信息
     */
    public String getReturnMsg() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.result_code</code>. 业务结果
     */
    public EpWechatPayRefundRecord setResultCode(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.result_code</code>. 业务结果
     */
    public String getResultCode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.err_code</code>. 错误代码
     */
    public EpWechatPayRefundRecord setErrCode(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.err_code</code>. 错误代码
     */
    public String getErrCode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.err_code_des</code>. 错误代码描述
     */
    public EpWechatPayRefundRecord setErrCodeDes(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.err_code_des</code>. 错误代码描述
     */
    public String getErrCodeDes() {
        return (String) get(13);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.refund_id</code>. 微信退款单号
     */
    public EpWechatPayRefundRecord setRefundId(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.refund_id</code>. 微信退款单号
     */
    public String getRefundId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.notify_return_code</code>. 通知返回状态码
     */
    public EpWechatPayRefundRecord setNotifyReturnCode(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.notify_return_code</code>. 通知返回状态码
     */
    public String getNotifyReturnCode() {
        return (String) get(15);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.notify_return_msg</code>. 返回信息
     */
    public EpWechatPayRefundRecord setNotifyReturnMsg(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.notify_return_msg</code>. 返回信息
     */
    public String getNotifyReturnMsg() {
        return (String) get(16);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.refund_status</code>.
     */
    public EpWechatPayRefundRecord setRefundStatus(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.refund_status</code>.
     */
    public String getRefundStatus() {
        return (String) get(17);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.success_time</code>. 退款成功时间
     */
    public EpWechatPayRefundRecord setSuccessTime(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.success_time</code>. 退款成功时间
     */
    public String getSuccessTime() {
        return (String) get(18);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.refund_recv_accout</code>. 退款入账账户
     */
    public EpWechatPayRefundRecord setRefundRecvAccout(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.refund_recv_accout</code>. 退款入账账户
     */
    public String getRefundRecvAccout() {
        return (String) get(19);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.refund_account</code>. 退款资金来源
     */
    public EpWechatPayRefundRecord setRefundAccount(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.refund_account</code>. 退款资金来源
     */
    public String getRefundAccount() {
        return (String) get(20);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.create_at</code>. 创建时间
     */
    public EpWechatPayRefundRecord setCreateAt(Timestamp value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(21);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.update_at</code>. 更新时间
     */
    public EpWechatPayRefundRecord setUpdateAt(Timestamp value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(22);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.remark</code>. 备注
     */
    public EpWechatPayRefundRecord setRemark(String value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(23);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.del_flag</code>. 删除标记
     */
    public EpWechatPayRefundRecord setDelFlag(Boolean value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.del_flag</code>. 删除标记
     */
    public Boolean getDelFlag() {
        return (Boolean) get(24);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_refund.version</code>.
     */
    public EpWechatPayRefundRecord setVersion(Long value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_refund.version</code>.
     */
    public Long getVersion() {
        return (Long) get(25);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EpWechatPayRefundRecord
     */
    public EpWechatPayRefundRecord() {
        super(EpWechatPayRefund.EP_WECHAT_PAY_REFUND);
    }

    /**
     * Create a detached, initialised EpWechatPayRefundRecord
     */
    public EpWechatPayRefundRecord(Long id, String appid, String mchId, String outTradeNo, String transactionId, String outRefundNo, Integer totalFee, Integer refundFee, String refundDesc, String returnCode, String returnMsg, String resultCode, String errCode, String errCodeDes, String refundId, String notifyReturnCode, String notifyReturnMsg, String refundStatus, String successTime, String refundRecvAccout, String refundAccount, Timestamp createAt, Timestamp updateAt, String remark, Boolean delFlag, Long version) {
        super(EpWechatPayRefund.EP_WECHAT_PAY_REFUND);

        set(0, id);
        set(1, appid);
        set(2, mchId);
        set(3, outTradeNo);
        set(4, transactionId);
        set(5, outRefundNo);
        set(6, totalFee);
        set(7, refundFee);
        set(8, refundDesc);
        set(9, returnCode);
        set(10, returnMsg);
        set(11, resultCode);
        set(12, errCode);
        set(13, errCodeDes);
        set(14, refundId);
        set(15, notifyReturnCode);
        set(16, notifyReturnMsg);
        set(17, refundStatus);
        set(18, successTime);
        set(19, refundRecvAccout);
        set(20, refundAccount);
        set(21, createAt);
        set(22, updateAt);
        set(23, remark);
        set(24, delFlag);
        set(25, version);
    }
}
