/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.repository.domain.tables.records;


import com.ep.domain.repository.domain.tables.EpWeixinUser;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EpWeixinUserRecord extends UpdatableRecordImpl<EpWeixinUserRecord> implements Record6<Long, String, String, Timestamp, Boolean, Boolean> {

    private static final long serialVersionUID = -1850785035;

    /**
     * Setter for <code>ep.ep_weixin_user.id</code>. pk
     */
    public EpWeixinUserRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_weixin_user.id</code>. pk
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ep.ep_weixin_user.open_id</code>.
     */
    public EpWeixinUserRecord setOpenId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_weixin_user.open_id</code>.
     */
    public String getOpenId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ep.ep_weixin_user.remark</code>.
     */
    public EpWeixinUserRecord setRemark(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_weixin_user.remark</code>.
     */
    public String getRemark() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ep.ep_weixin_user.create_at</code>. 创建时间
     */
    public EpWeixinUserRecord setCreateAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_weixin_user.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>ep.ep_weixin_user.del_flag</code>. 删除标记
     */
    public EpWeixinUserRecord setDelFlag(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_weixin_user.del_flag</code>. 删除标记
     */
    public Boolean getDelFlag() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>ep.ep_weixin_user.version</code>. 版本号
     */
    public EpWeixinUserRecord setVersion(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_weixin_user.version</code>. 版本号
     */
    public Boolean getVersion() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, Timestamp, Boolean, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, Timestamp, Boolean, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EpWeixinUser.EP_WEIXIN_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EpWeixinUser.EP_WEIXIN_USER.OPEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EpWeixinUser.EP_WEIXIN_USER.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return EpWeixinUser.EP_WEIXIN_USER.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return EpWeixinUser.EP_WEIXIN_USER.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return EpWeixinUser.EP_WEIXIN_USER.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWeixinUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWeixinUserRecord value2(String value) {
        setOpenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWeixinUserRecord value3(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWeixinUserRecord value4(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWeixinUserRecord value5(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWeixinUserRecord value6(Boolean value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWeixinUserRecord values(Long value1, String value2, String value3, Timestamp value4, Boolean value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EpWeixinUserRecord
     */
    public EpWeixinUserRecord() {
        super(EpWeixinUser.EP_WEIXIN_USER);
    }

    /**
     * Create a detached, initialised EpWeixinUserRecord
     */
    public EpWeixinUserRecord(Long id, String openId, String remark, Timestamp createAt, Boolean delFlag, Boolean version) {
        super(EpWeixinUser.EP_WEIXIN_USER);

        set(0, id);
        set(1, openId);
        set(2, remark);
        set(3, createAt);
        set(4, delFlag);
        set(5, version);
    }
}
