/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.repository.domain.tables.records;


import com.ep.domain.repository.domain.enums.EpWechatFormBizType;
import com.ep.domain.repository.domain.tables.EpWechatForm;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 微信form提交关联表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EpWechatFormRecord extends UpdatableRecordImpl<EpWechatFormRecord> implements Record11<Long, String, String, Long, EpWechatFormBizType, Timestamp, Timestamp, Timestamp, String, Boolean, Long> {

    private static final long serialVersionUID = -2040957653;

    /**
     * Setter for <code>ep.ep_wechat_form.id</code>.
     */
    public EpWechatFormRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_form.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ep.ep_wechat_form.form_id</code>. 小程序formid
     */
    public EpWechatFormRecord setFormId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_form.form_id</code>. 小程序formid
     */
    public String getFormId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ep.ep_wechat_form.touser</code>. 微信openid
     */
    public EpWechatFormRecord setTouser(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_form.touser</code>. 微信openid
     */
    public String getTouser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ep.ep_wechat_form.source_id</code>. 业务id
     */
    public EpWechatFormRecord setSourceId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_form.source_id</code>. 业务id
     */
    public Long getSourceId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>ep.ep_wechat_form.biz_type</code>. 订单;
     */
    public EpWechatFormRecord setBizType(EpWechatFormBizType value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_form.biz_type</code>. 订单;
     */
    public EpWechatFormBizType getBizType() {
        return (EpWechatFormBizType) get(4);
    }

    /**
     * Setter for <code>ep.ep_wechat_form.expire_time</code>. 过期时间
     */
    public EpWechatFormRecord setExpireTime(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_form.expire_time</code>. 过期时间
     */
    public Timestamp getExpireTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>ep.ep_wechat_form.create_at</code>. 创建时间
     */
    public EpWechatFormRecord setCreateAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_form.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>ep.ep_wechat_form.update_at</code>. 更新时间
     */
    public EpWechatFormRecord setUpdateAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_form.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>ep.ep_wechat_form.remark</code>. 备注
     */
    public EpWechatFormRecord setRemark(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_form.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ep.ep_wechat_form.del_flag</code>. 删除标记
     */
    public EpWechatFormRecord setDelFlag(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_form.del_flag</code>. 删除标记
     */
    public Boolean getDelFlag() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>ep.ep_wechat_form.version</code>. 版本号
     */
    public EpWechatFormRecord setVersion(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_form.version</code>. 版本号
     */
    public Long getVersion() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, Long, EpWechatFormBizType, Timestamp, Timestamp, Timestamp, String, Boolean, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, Long, EpWechatFormBizType, Timestamp, Timestamp, Timestamp, String, Boolean, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EpWechatForm.EP_WECHAT_FORM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EpWechatForm.EP_WECHAT_FORM.FORM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EpWechatForm.EP_WECHAT_FORM.TOUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return EpWechatForm.EP_WECHAT_FORM.SOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EpWechatFormBizType> field5() {
        return EpWechatForm.EP_WECHAT_FORM.BIZ_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return EpWechatForm.EP_WECHAT_FORM.EXPIRE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return EpWechatForm.EP_WECHAT_FORM.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return EpWechatForm.EP_WECHAT_FORM.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return EpWechatForm.EP_WECHAT_FORM.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return EpWechatForm.EP_WECHAT_FORM.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return EpWechatForm.EP_WECHAT_FORM.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTouser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getSourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormBizType value5() {
        return getBizType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getExpireTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord value2(String value) {
        setFormId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord value3(String value) {
        setTouser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord value4(Long value) {
        setSourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord value5(EpWechatFormBizType value) {
        setBizType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord value6(Timestamp value) {
        setExpireTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord value7(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord value8(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord value9(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord value10(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord value11(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatFormRecord values(Long value1, String value2, String value3, Long value4, EpWechatFormBizType value5, Timestamp value6, Timestamp value7, Timestamp value8, String value9, Boolean value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EpWechatFormRecord
     */
    public EpWechatFormRecord() {
        super(EpWechatForm.EP_WECHAT_FORM);
    }

    /**
     * Create a detached, initialised EpWechatFormRecord
     */
    public EpWechatFormRecord(Long id, String formId, String touser, Long sourceId, EpWechatFormBizType bizType, Timestamp expireTime, Timestamp createAt, Timestamp updateAt, String remark, Boolean delFlag, Long version) {
        super(EpWechatForm.EP_WECHAT_FORM);

        set(0, id);
        set(1, formId);
        set(2, touser);
        set(3, sourceId);
        set(4, bizType);
        set(5, expireTime);
        set(6, createAt);
        set(7, updateAt);
        set(8, remark);
        set(9, delFlag);
        set(10, version);
    }
}
