/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.repository.domain.tables.records;


import com.ep.domain.repository.domain.enums.EpWechatPayWithdrawStatus;
import com.ep.domain.repository.domain.tables.EpWechatPayWithdraw;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Timestamp;


/**
 * 微信支付提现申请
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EpWechatPayWithdrawRecord extends UpdatableRecordImpl<EpWechatPayWithdrawRecord> implements Record16<Long, Long, Long, BigDecimal, Integer, Integer, Integer, BigDecimal, BigDecimal, String, EpWechatPayWithdrawStatus, Timestamp, Timestamp, String, Boolean, Long> {

    private static final long serialVersionUID = -1823080549;

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.id</code>. 主键
     */
    public EpWechatPayWithdrawRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.course_id</code>. 课程id
     */
    public EpWechatPayWithdrawRecord setCourseId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.course_id</code>. 课程id
     */
    public Long getCourseId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.class_id</code>. 班次id
     */
    public EpWechatPayWithdrawRecord setClassId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.class_id</code>. 班次id
     */
    public Long getClassId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.total_amount</code>. 提现总金额
     */
    public EpWechatPayWithdrawRecord setTotalAmount(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.total_amount</code>. 提现总金额
     */
    public BigDecimal getTotalAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.order_num</code>. 报名订单数
     */
    public EpWechatPayWithdrawRecord setOrderNum(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.order_num</code>. 报名订单数
     */
    public Integer getOrderNum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.offline_pay_num</code>. 线下支付订单数
     */
    public EpWechatPayWithdrawRecord setOfflinePayNum(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.offline_pay_num</code>. 线下支付订单数
     */
    public Integer getOfflinePayNum() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.wechat_pay_num</code>. 微信支付订单数
     */
    public EpWechatPayWithdrawRecord setWechatPayNum(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.wechat_pay_num</code>. 微信支付订单数
     */
    public Integer getWechatPayNum() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.wechat_pay_fee</code>. 微信支付手续费
     */
    public EpWechatPayWithdrawRecord setWechatPayFee(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.wechat_pay_fee</code>. 微信支付手续费
     */
    public BigDecimal getWechatPayFee() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.withdraw_fee</code>. 提现手续费
     */
    public EpWechatPayWithdrawRecord setWithdrawFee(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.withdraw_fee</code>. 提现手续费
     */
    public BigDecimal getWithdrawFee() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.withdraw_no</code>. 提现订单号
     */
    public EpWechatPayWithdrawRecord setWithdrawNo(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.withdraw_no</code>. 提现订单号
     */
    public String getWithdrawNo() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.status</code>. 提现状态
     */
    public EpWechatPayWithdrawRecord setStatus(EpWechatPayWithdrawStatus value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.status</code>. 提现状态
     */
    public EpWechatPayWithdrawStatus getStatus() {
        return (EpWechatPayWithdrawStatus) get(10);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.create_at</code>. 创建时间
     */
    public EpWechatPayWithdrawRecord setCreateAt(Timestamp value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.update_at</code>. 更新时间
     */
    public EpWechatPayWithdrawRecord setUpdateAt(Timestamp value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.remark</code>. 备注
     */
    public EpWechatPayWithdrawRecord setRemark(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(13);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.del_flag</code>. 删除标记
     */
    public EpWechatPayWithdrawRecord setDelFlag(Boolean value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.del_flag</code>. 删除标记
     */
    public Boolean getDelFlag() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>ep.ep_wechat_pay_withdraw.version</code>.
     */
    public EpWechatPayWithdrawRecord setVersion(Long value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ep.ep_wechat_pay_withdraw.version</code>.
     */
    public Long getVersion() {
        return (Long) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, Long, Long, BigDecimal, Integer, Integer, Integer, BigDecimal, BigDecimal, String, EpWechatPayWithdrawStatus, Timestamp, Timestamp, String, Boolean, Long> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, Long, Long, BigDecimal, Integer, Integer, Integer, BigDecimal, BigDecimal, String, EpWechatPayWithdrawStatus, Timestamp, Timestamp, String, Boolean, Long> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.TOTAL_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.ORDER_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.OFFLINE_PAY_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.WECHAT_PAY_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.WECHAT_PAY_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.WITHDRAW_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.WITHDRAW_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EpWechatPayWithdrawStatus> field11() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field15() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getTotalAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getOrderNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getOfflinePayNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getWechatPayNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getWechatPayFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getWithdrawFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getWithdrawNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawStatus value11() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value15() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value2(Long value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value3(Long value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value4(BigDecimal value) {
        setTotalAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value5(Integer value) {
        setOrderNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value6(Integer value) {
        setOfflinePayNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value7(Integer value) {
        setWechatPayNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value8(BigDecimal value) {
        setWechatPayFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value9(BigDecimal value) {
        setWithdrawFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value10(String value) {
        setWithdrawNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value11(EpWechatPayWithdrawStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value12(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value13(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value14(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value15(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord value16(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EpWechatPayWithdrawRecord values(Long value1, Long value2, Long value3, BigDecimal value4, Integer value5, Integer value6, Integer value7, BigDecimal value8, BigDecimal value9, String value10, EpWechatPayWithdrawStatus value11, Timestamp value12, Timestamp value13, String value14, Boolean value15, Long value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EpWechatPayWithdrawRecord
     */
    public EpWechatPayWithdrawRecord() {
        super(EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW);
    }

    /**
     * Create a detached, initialised EpWechatPayWithdrawRecord
     */
    public EpWechatPayWithdrawRecord(Long id, Long courseId, Long classId, BigDecimal totalAmount, Integer orderNum, Integer offlinePayNum, Integer wechatPayNum, BigDecimal wechatPayFee, BigDecimal withdrawFee, String withdrawNo, EpWechatPayWithdrawStatus status, Timestamp createAt, Timestamp updateAt, String remark, Boolean delFlag, Long version) {
        super(EpWechatPayWithdraw.EP_WECHAT_PAY_WITHDRAW);

        set(0, id);
        set(1, courseId);
        set(2, classId);
        set(3, totalAmount);
        set(4, orderNum);
        set(5, offlinePayNum);
        set(6, wechatPayNum);
        set(7, wechatPayFee);
        set(8, withdrawFee);
        set(9, withdrawNo);
        set(10, status);
        set(11, createAt);
        set(12, updateAt);
        set(13, remark);
        set(14, delFlag);
        set(15, version);
    }
}
