/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;


/**
 * 文件表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class EpFilePo extends AbstractBasePojo {

    @JsonIgnore
    private Long id;
    private String preCode;
    private String fileName;
    private String fileUrl;
    @JsonIgnore
    private Short bizTypeCode;
    @JsonIgnore
    private Long sourceId;
    private Integer sort;
    @JsonIgnore
    private Timestamp createAt;
    @JsonIgnore
    private Timestamp updateAt;
    @JsonIgnore
    private String remark;
    @JsonIgnore
    private Boolean delFlag;
    @JsonIgnore
    private Long version;

}
