/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;


/**
 * 孩子签名表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class EpMemberChildSignPo extends AbstractBasePojo {

    private Long id;
    private Long childId;
    private String content;
    private Timestamp createAt;
    private Timestamp updateAt;
    private String remark;
    private Boolean delFlag;
    private Long version;

}
