/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import com.ep.domain.repository.domain.enums.EpMemberChildChildSex;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;


/**
 * 孩子信息表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class EpMemberChildPo extends AbstractBasePojo {

    private Long id;
    private Long memberId;
    private String childNickName;
    private String childTrueName;
    private EpMemberChildChildSex childSex;
    private Timestamp childBirthday;
    private String childIdentity;
    private String currentSchool;
    private String currentClass;
    private String relationship;
    private Timestamp createAt;
    private Timestamp updateAt;
    private String remark;
    private Boolean delFlag;
    private Long version;

}
