/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 机构类目表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EpOrganCatalogPo implements Serializable {

    private static final long serialVersionUID = 966446288;

    private Long id;
    private Long ognId;
    private Long courseCatalogId;
    private Timestamp createAt;
    private Timestamp updateAt;
    private String remark;
    private Boolean delFlag;
    private Long version;

    public EpOrganCatalogPo() {
    }

    public EpOrganCatalogPo(EpOrganCatalogPo value) {
        this.id = value.id;
        this.ognId = value.ognId;
        this.courseCatalogId = value.courseCatalogId;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.remark = value.remark;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public EpOrganCatalogPo(
            Long id,
            Long ognId,
            Long courseCatalogId,
            Timestamp createAt,
            Timestamp updateAt,
            String remark,
            Boolean delFlag,
            Long version
    ) {
        this.id = id;
        this.ognId = ognId;
        this.courseCatalogId = courseCatalogId;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.remark = remark;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public EpOrganCatalogPo setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getOgnId() {
        return this.ognId;
    }

    public EpOrganCatalogPo setOgnId(Long ognId) {
        this.ognId = ognId;
        return this;
    }

    public Long getCourseCatalogId() {
        return this.courseCatalogId;
    }

    public EpOrganCatalogPo setCourseCatalogId(Long courseCatalogId) {
        this.courseCatalogId = courseCatalogId;
        return this;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public EpOrganCatalogPo setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
        return this;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public EpOrganCatalogPo setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
        return this;
    }

    public String getRemark() {
        return this.remark;
    }

    public EpOrganCatalogPo setRemark(String remark) {
        this.remark = remark;
        return this;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public EpOrganCatalogPo setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
        return this;
    }

    public Long getVersion() {
        return this.version;
    }

    public EpOrganCatalogPo setVersion(Long version) {
        this.version = version;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EpOrganCatalogPo (");

        sb.append(id);
        sb.append(", ").append(ognId);
        sb.append(", ").append(courseCatalogId);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(remark);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
