/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import com.ep.domain.repository.domain.enums.EpOrganClassScheduleCommentCommentType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;


/**
 * 机构行程评论表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class EpOrganClassScheduleCommentPo extends AbstractBasePojo {

    private Long id;
    private Long pId;
    private Long classScheduleId;
    private EpOrganClassScheduleCommentCommentType commentType;
    private String content;
    private Long launchMemberId;
    private Long replyMemberId;
    private Timestamp createAt;
    private Timestamp updateAt;
    private String remark;
    private Boolean delFlag;
    private Long version;

}
