/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.repository.domain.enums.EpOrganClassScheduleScheduleStatus;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 机构行程信息表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EpOrganClassSchedulePo implements Serializable {

    private static final long serialVersionUID = -500527880;

    private Long id;
    private Long classId;
    private Long childId;
    private EpOrganClassScheduleScheduleStatus scheduleStatus;
    private Timestamp createAt;
    private Timestamp updateAt;
    private String remark;
    private Boolean delFlag;
    private Long version;

    public EpOrganClassSchedulePo() {
    }

    public EpOrganClassSchedulePo(EpOrganClassSchedulePo value) {
        this.id = value.id;
        this.classId = value.classId;
        this.childId = value.childId;
        this.scheduleStatus = value.scheduleStatus;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.remark = value.remark;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public EpOrganClassSchedulePo(
            Long id,
            Long classId,
            Long childId,
            EpOrganClassScheduleScheduleStatus scheduleStatus,
            Timestamp createAt,
            Timestamp updateAt,
            String remark,
            Boolean delFlag,
            Long version
    ) {
        this.id = id;
        this.classId = classId;
        this.childId = childId;
        this.scheduleStatus = scheduleStatus;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.remark = remark;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public EpOrganClassSchedulePo setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getClassId() {
        return this.classId;
    }

    public EpOrganClassSchedulePo setClassId(Long classId) {
        this.classId = classId;
        return this;
    }

    public Long getChildId() {
        return this.childId;
    }

    public EpOrganClassSchedulePo setChildId(Long childId) {
        this.childId = childId;
        return this;
    }

    public EpOrganClassScheduleScheduleStatus getScheduleStatus() {
        return this.scheduleStatus;
    }

    public EpOrganClassSchedulePo setScheduleStatus(EpOrganClassScheduleScheduleStatus scheduleStatus) {
        this.scheduleStatus = scheduleStatus;
        return this;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public EpOrganClassSchedulePo setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
        return this;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public EpOrganClassSchedulePo setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
        return this;
    }

    public String getRemark() {
        return this.remark;
    }

    public EpOrganClassSchedulePo setRemark(String remark) {
        this.remark = remark;
        return this;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public EpOrganClassSchedulePo setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
        return this;
    }

    public Long getVersion() {
        return this.version;
    }

    public EpOrganClassSchedulePo setVersion(Long version) {
        this.version = version;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EpOrganClassSchedulePo (");

        sb.append(id);
        sb.append(", ").append(classId);
        sb.append(", ").append(childId);
        sb.append(", ").append(scheduleStatus);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(remark);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
