/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.sql.Timestamp;


/**
 * 机构课程sku表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class EpOrganCourseSkuPo extends AbstractBasePojo {

    private Long id;
    private Long ognId;
    private Long courseId;
    private String skuName;
    private BigDecimal skuPrize;
    private BigDecimal discountAmount;
    private Boolean enterLimitFlag;
    private Integer enterRequireNum;
    private Integer enteredNum;
    private Integer courseNum;
    private String remark;
    private Timestamp createAt;
    private Timestamp updateAt;
    private Boolean delFlag;
    private Long version;

}
