/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 机构课程团队信息表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EpOrganCourseTeamPo implements Serializable {

    private static final long serialVersionUID = -499021271;

    private Long id;
    private Long courseId;
    private Long ognAccountId;
    private Integer sort;
    private Timestamp createAt;
    private Timestamp updateAt;
    private String remark;
    private Boolean delFlag;
    private Long version;

    public EpOrganCourseTeamPo() {
    }

    public EpOrganCourseTeamPo(EpOrganCourseTeamPo value) {
        this.id = value.id;
        this.courseId = value.courseId;
        this.ognAccountId = value.ognAccountId;
        this.sort = value.sort;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.remark = value.remark;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public EpOrganCourseTeamPo(
            Long id,
            Long courseId,
            Long ognAccountId,
            Integer sort,
            Timestamp createAt,
            Timestamp updateAt,
            String remark,
            Boolean delFlag,
            Long version
    ) {
        this.id = id;
        this.courseId = courseId;
        this.ognAccountId = ognAccountId;
        this.sort = sort;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.remark = remark;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public EpOrganCourseTeamPo setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getCourseId() {
        return this.courseId;
    }

    public EpOrganCourseTeamPo setCourseId(Long courseId) {
        this.courseId = courseId;
        return this;
    }

    public Long getOgnAccountId() {
        return this.ognAccountId;
    }

    public EpOrganCourseTeamPo setOgnAccountId(Long ognAccountId) {
        this.ognAccountId = ognAccountId;
        return this;
    }

    public Integer getSort() {
        return this.sort;
    }

    public EpOrganCourseTeamPo setSort(Integer sort) {
        this.sort = sort;
        return this;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public EpOrganCourseTeamPo setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
        return this;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public EpOrganCourseTeamPo setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
        return this;
    }

    public String getRemark() {
        return this.remark;
    }

    public EpOrganCourseTeamPo setRemark(String remark) {
        this.remark = remark;
        return this;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public EpOrganCourseTeamPo setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
        return this;
    }

    public Long getVersion() {
        return this.version;
    }

    public EpOrganCourseTeamPo setVersion(Long version) {
        this.version = version;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EpOrganCourseTeamPo (");

        sb.append(id);
        sb.append(", ").append(courseId);
        sb.append(", ").append(ognAccountId);
        sb.append(", ").append(sort);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(remark);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
