/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;


/**
 * 机构配置表
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class EpOrganConfigPo extends AbstractBasePojo {

    private Long id;
    private Long ognId;
    private Boolean privateFlag;
    private Boolean supportTag;
    private Timestamp createAt;
    private Timestamp updateAt;
    private String remark;
    private Boolean delFlag;
    private Long version;

}
