/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import com.ep.domain.repository.domain.enums.EpOrderStatus;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.sql.Timestamp;


/**
 * 订单表
 */
@AllArgsConstructor
@NoArgsConstructor
@Data
public class EpOrderPo extends AbstractBasePojo {

    private Long id;
    private Long memberId;
    private Long childId;
    private Long ognId;
    private Long courseId;
    private Long classId;
    private BigDecimal prize;
    private EpOrderStatus status;
    private Timestamp authTime;
    private Timestamp cancelTime;
    private Timestamp createAt;
    @JsonIgnore
    private Timestamp updateAt;
    private String remark;
    @JsonIgnore
    private Boolean delFlag;
    @JsonIgnore
    private Long version;

    public String getStatusText() {
        if (EpOrderStatus.save.equals(status)) {
            return "报名中";
        } else if (EpOrderStatus.success.equals(status)) {
            return "报名成功";
        } else if (EpOrderStatus.opening.equals(status)) {
            return "学习中";
        } else if (EpOrderStatus.end.equals(status)) {
            return "已结束";
        } else if (EpOrderStatus.cancel.equals(status)) {
            return "用户已取消";
        } else if (EpOrderStatus.refuse.equals(status)) {
            return "机构已取消";
        }
        return null;
    }
}
