/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;


/**
 * 用户-角色
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class EpSystemUserRolePo extends AbstractBasePojo {

    private static final long serialVersionUID = 538120445;

    private Long      id;
    private Long      userId;
    private Long      roleId;
    private Timestamp createAt;
    private Timestamp updateAt;
    private Boolean   delFlag;
    private Long      version;


}
