/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 角色权限表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@AllArgsConstructor
@NoArgsConstructor
@Data
public class EpSystemRoleAuthorityPo extends AbstractBasePojo {

    private static final long serialVersionUID = 1076659516;

    private Long      id;
    private Long      roleId;
    private String    role;
    private Long      menuId;
    private String    authority;
    private Timestamp createAt;
    private Timestamp updateAt;
    private String    remark;
    private Boolean   delFlag;
    private Long      version;

}
