/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.sql.Timestamp;


/**
 * 微信支付对账表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class EpWechatPayBillPo extends AbstractBasePojo {

    private Long id;
    private Integer billDate;
    private Integer totalNum;
    private BigDecimal totalAmount;
    private BigDecimal totalRefundAmount;
    private BigDecimal totalCouponRefundAmount;
    private BigDecimal totalPoundage;
    private String returnCode;
    private String returnMsg;
    private Timestamp createAt;
    private Timestamp updateAt;
    private String remark;
    private Boolean delFlag;
    private Long version;

}
