/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;


/**
 * 微信公众号用户
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class EpWeixinUserPo extends AbstractBasePojo {
    private Long id;
    private String openId;
    private String remark;
    private Timestamp createAt;
    private Boolean delFlag;
    private Boolean version;
}
