/*
 * This file is generated by jOOQ.
*/
package com.ep.domain.pojo.po;


import com.ep.domain.pojo.AbstractBasePojo;
import com.ep.domain.repository.domain.enums.EpWechatFormBizType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;


/**
 * 微信form提交关联表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class EpWechatFormPo extends AbstractBasePojo {
    private Long id;
    private String formId;
    private String touser;
    private Long sourceId;
    private EpWechatFormBizType bizType;
    private Timestamp expireTime;
    private Timestamp createAt;
    private Timestamp updateAt;
    private String remark;
    private Boolean delFlag;
    private Long version;
}
